// components/app/web-components/llmplayground-webcomponent/src/error-page.tsx
/** ================================================================================================================# *
 * # ===============================================================================================================# *
 * # Copyright 2025 Infosys Ltd.                                                                                    # *
 * # Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  # *
 * # http://www.apache.org/licenses/                                                                                # *
 * # ===============================================================================================================# *
 **/
import { useRouteError } from "react-router-dom"

export default function ErrorPage() {
  const error = useRouteError()
  console.error(error)

  return (
    <div id="error-page">
      <h1>Oops!</h1>
      <p>Sorry, an unexpected error has occurred.</p>
      <p>
        <i>{error.statusText || error.message}</i>
      </p>
    </div>
  )
}

// components/app/transformerfoundry/src/app/component/error-page/error-page.component.ts
/** ================================================================================================================# *
 * # ===============================================================================================================# *
 * # Copyright 2025 Infosys Ltd.                                                                                    # *
 * # Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  # *
 * # http://www.apache.org/licenses/                                                                                # *
 * # ===============================================================================================================# *
 **/

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-error-page',
  templateUrl: './error-page.component.html',
  styleUrls: ['./error-page.component.scss']
})
export class ErrorPageComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}


<!--
 ================================================================================================================
 # ===============================================================================================================
 # Copyright 2025 Infosys Ltd.
 # Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at
 # http://www.apache.org/licenses/
 # ===============================================================================================================
 ================================================================================================================
-->
<div style="display: flex; align-items: center; justify-content: center; font-style: italic;">
    Unfortunately, we couldn't find the page...
</div>
